<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.8" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
  </ItemGroup>

</Project>
